### ISSUE TITLE
xdmod ticket #29597 Data in the interface

### ISSUE THREAD

**Issue by rob-baron** [CCI-MOC/xdmod-cntr#207]

**Comment by rob-baron** [comment]
Robert Bartlett Baron, reported over 1 year ago
Ok, I have shredded and ingested from the reference xdmod-openstack file (https://github.com/ubccr/xdmod/tree/xdmod10.0/tests/artifacts/xdmod/referencedata).  I brought up the xdmod interface, it is running without complaining that there is no data, however, it doesn't display any data for any time period.  

which database values need to match with values in the file?

Gregary Dean , said over 1 year ago
Ticket:  https://help.xdmod.org/support/tickets/29597

Hi Robert,

There are a couple of things to note. The first is when running xdmod-shredder to make sure you specify the correct resource using the -r flag. It should be the resource you previously added. The second is that most of the reference data is from April 2018 so you have to look quite a ways back to see it. You said it didn't show for any time range so I'm assuming you did look back to at least April 2018 but just wanted to make sure. 

As for more troubleshooting, can you check the following tables to see if they have data in them?

- modw_cloud.openstack_staging_event
- modw_cloud.event
- modw_cloud.session_records

Do you still have the commands you ran when shredding and ingesting the data? Can you send those to me?

Thanks,
Greg
Robert Bartlett Baron , said over 1 year ago
OK, shredding doesn't work:

xdmod-shredder -f openstack -d openstack -r Cloud
2022-04-04 15:28:33 [notice] xdmod-shredder start (process_start_time: 2022-04-04 15:28:33)
2022-04-04 15:28:37 [notice] Start processing section 'xdmod.jobs-common'
2022-04-04 15:28:37 [notice] (action: xdmod.jobs-common.JobsTableManagement (ETL\Maintenance\ManageTables), start_time: 1649086117.1748, end_time: 1649086117.2365, elapsed_time: 0.06171)
2022-04-04 15:28:37 [notice] (action: xdmod.jobs-common.CountableTypeIngestor (ETL\Ingestor\StructuredFileIngestor), start_time: 1649086117.3197, end_time: 1649086117.5459, elapsed_time: 0.22615, records_examined: 5, records_loaded: 5)
2022-04-04 15:28:37 [notice] (action: xdmod.jobs-common.JobRecordTypeIngestor (ETL\Ingestor\StructuredFileIngestor), start_time: 1649086117.6095, end_time: 1649086117.7845, elapsed_time: 0.17498, records_examined: 5, records_loaded: 5)
2022-04-04 15:28:38 [notice] (action: xdmod.jobs-common.JobTaskTypeIngestor (ETL\Ingestor\StructuredFileIngestor), start_time: 1649086117.8456, end_time: 1649086118.0374, elapsed_time: 0.19177, records_examined: 5, records_loaded: 5)
2022-04-04 15:28:38 [notice] (action: xdmod.jobs-common.UnitIngestor (ETL\Ingestor\StructuredFileIngestor), start_time: 1649086118.1047, end_time: 1649086118.2985, elapsed_time: 0.1938, records_examined: 6, records_loaded: 6)
2022-04-04 15:28:38 [notice] (action: xdmod.jobs-common.SubmissionVenueIngestor (ETL\Ingestor\StructuredFileIngestor), start_time: 1649086118.357, end_time: 1649086118.5486, elapsed_time: 0.19155, records_examined: 4, records_loaded: 4)
2022-04-04 15:28:38 [notice] Finished processing section 'xdmod.jobs-common'
2022-04-04 15:28:38 [notice] Start processing section 'xdmod.ingest-organizations'
2022-04-04 15:28:38 [notice] (action: xdmod.ingest-organizations.IngestOrganizationConfig (ETL\Ingestor\StructuredFileIngestor), start_time: 1649086118.6612, end_time: 1649086118.7848, elapsed_time: 0.12365, records_examined: 1, records_loaded: 1)
2022-04-04 15:28:38 [notice] (action: xdmod.ingest-organizations.IngestOrganizationHpcdb (ETL\Ingestor\DatabaseIngestor), start_time: 1649086118.8448, end_time: 1649086118.9192, elapsed_time: 0.07448, records_examined: 0, records_loaded: 0)
2022-04-04 15:28:39 [notice] (action: xdmod.ingest-organizations.IngestOrgranizationDatawarehouse (ETL\Ingestor\DatabaseIngestor), start_time: 1649086118.9853, end_time: 1649086119.2964, elapsed_time: 0.31109, records_examined: 1, records_loaded: 1)
2022-04-04 15:28:39 [notice] Finished processing section 'xdmod.ingest-organizations'
2022-04-04 15:28:39 [notice] Start processing section 'xdmod.ingest-resource-types'
2022-04-04 15:28:39 [notice] (action: xdmod.ingest-resource-types.ResourceTypesStagingTableManagement (ETL\Maintenance\ManageTables), start_time: 1649086119.4154, end_time: 1649086119.4365, elapsed_time: 0.02118)
2022-04-04 15:28:39 [notice] Processing SQL file '/etc/xdmod/etl/etl_sql.d/cloud_openstack/unknown_resource_type.sql' using delimiter '//' containing 2 statements
2022-04-04 15:28:39 [notice] Finished Processing 2 SQL statements
2022-04-04 15:28:39 [notice] (action: xdmod.ingest-resource-types.ResourceTypesStagingUnknown (ETL\Maintenance\ExecuteSql), start_time: 1649086119.4833, end_time: 1649086119.5873, elapsed_time: 0.10402)
2022-04-04 15:28:39 [notice] (action: xdmod.ingest-resource-types.ResourceTypesStaging (ETL\Ingestor\StructuredFileIngestor), start_time: 1649086119.642, end_time: 1649086119.7539, elapsed_time: 0.1119, records_examined: 12, records_loaded: 12)
2022-04-04 15:28:39 [notice] (action: xdmod.ingest-resource-types.ResourceTypesHpcdb (ETL\Ingestor\DatabaseIngestor), start_time: 1649086119.8167, end_time: 1649086119.8894, elapsed_time: 0.07274, records_examined: 0, records_loaded: 0)
2022-04-04 15:28:40 [notice] (action: xdmod.ingest-resource-types.ResourceTypesDatawarehouse (ETL\Ingestor\DatabaseIngestor), start_time: 1649086119.9549, end_time: 1649086120.0291, elapsed_time: 0.07413, records_examined: 0, records_loaded: 0)
2022-04-04 15:28:40 [notice] Finished processing section 'xdmod.ingest-resource-types'
2022-04-04 15:28:40 [notice] Start processing section 'xdmod.ingest-resources'
2022-04-04 15:28:40 [notice] (action: xdmod.ingest-resources.IngestResourceConfig (ETL\Ingestor\StructuredFileIngestor), start_time: 1649086120.1264, end_time: 1649086120.2017, elapsed_time: 0.07532, records_examined: 1, records_loaded: 1)
2022-04-04 15:28:40 [notice] (action: xdmod.ingest-resources.IngestResourcesStaging (ETL\Ingestor\DatabaseIngestor), start_time: 1649086120.2743, end_time: 1649086120.3394, elapsed_time: 0.06509, records_examined: 0, records_loaded: 0)
2022-04-04 15:28:40 [notice] (action: xdmod.ingest-resources.HpcdbIngestResources (ETL\Ingestor\DatabaseIngestor), start_time: 1649086120.4107, end_time: 1649086120.4879, elapsed_time: 0.07726, records_examined: 0, records_loaded: 0)
2022-04-04 15:28:40 [notice] (action: xdmod.ingest-resources.IngestResourcefact (ETL\Ingestor\DatabaseIngestor), start_time: 1649086120.5515, end_time: 1649086120.6279, elapsed_time: 0.07639, records_examined: 0, records_loaded: 0)
2022-04-04 15:28:40 [notice] (action: xdmod.ingest-resources.IngestResourceTypeRealmRelationsStaging (ETL\Ingestor\StructuredFileIngestor), start_time: 1649086120.686, end_time: 1649086120.8814, elapsed_time: 0.19542, records_examined: 9, records_loaded: 9)
2022-04-04 15:28:41 [notice] (action: xdmod.ingest-resources.IngestInitialRealms (ETL\Ingestor\DatabaseIngestor), start_time: 1649086120.94, end_time: 1649086121.0115, elapsed_time: 0.07158, records_examined: 0, records_loaded: 0)
2022-04-04 15:28:41 [notice] (action: xdmod.ingest-resources.IngestResourcefactRealmRelations (ETL\Ingestor\DatabaseIngestor), start_time: 1649086121.07, end_time: 1649086121.1917, elapsed_time: 0.12173, records_examined: 27, records_loaded: 27)
2022-04-04 15:28:41 [notice] Finished processing section 'xdmod.ingest-resources'
2022-04-04 15:28:41 [notice] Start processing section 'xdmod.jobs-cloud-common'
2022-04-04 15:28:41 [notice] Altering table `modw_cloud`.`event`
2022-04-04 15:28:41 [notice] Altering table `modw_cloud`.`cloud_resource_specs`
2022-04-04 15:28:41 [notice] Altering table `modw_cloud`.`session_records`
2022-04-04 15:28:41 [notice] (action: xdmod.jobs-cloud-common.CloudTableManagement (ETL\Maintenance\ManageTables), start_time: 1649086121.2821, end_time: 1649086121.63, elapsed_time: 0.3479)
2022-04-04 15:28:41 [notice] (action: xdmod.jobs-cloud-common.CloudAssetTypeInitializer (ETL\Ingestor\StructuredFileIngestor), start_time: 1649086121.6763, end_time: 1649086121.7445, elapsed_time: 0.06816, records_examined: 5, records_loaded: 5)
2022-04-04 15:28:41 [notice] (action: xdmod.jobs-cloud-common.CloudEventTypeInitializer (ETL\Ingestor\StructuredFileIngestor), start_time: 1649086121.814, end_time: 1649086121.9008, elapsed_time: 0.08671, records_examined: 65, records_loaded: 65)
2022-04-04 15:28:42 [notice] (action: xdmod.jobs-cloud-common.CloudRecordTypeInitializer (ETL\Ingestor\StructuredFileIngestor), start_time: 1649086121.9631, end_time: 1649086122.0369, elapsed_time: 0.07377, records_examined: 4, records_loaded: 4)
2022-04-04 15:28:42 [notice] (action: xdmod.jobs-cloud-common.CloudHostUnknownInitializer (ETL\Ingestor\StructuredFileIngestor), start_time: 1649086122.0919, end_time: 1649086122.161, elapsed_time: 0.06909, records_examined: 1, records_loaded: 1)
2022-04-04 15:28:42 [notice] (action: xdmod.jobs-cloud-common.CloudAccountUnknownInitializer (ETL\Ingestor\StructuredFileIngestor), start_time: 1649086122.2255, end_time: 1649086122.2948, elapsed_time: 0.06931, records_examined: 1, records_loaded: 1)
2022-04-04 15:28:42 [notice] (action: xdmod.jobs-cloud-common.CloudInstanceUnknownInitializer (ETL\Ingestor\StructuredFileIngestor), start_time: 1649086122.3606, end_time: 1649086122.433, elapsed_time: 0.07241, records_examined: 1, records_loaded: 1)
2022-04-04 15:28:42 [notice] (action: xdmod.jobs-cloud-common.CloudInstanceTypeUnknownInitializer (ETL\Ingestor\StructuredFileIngestor), start_time: 1649086122.4981, end_time: 1649086122.5726, elapsed_time: 0.07456, records_examined: 1, records_loaded: 1)
2022-04-04 15:28:42 [notice] (action: xdmod.jobs-cloud-common.CloudImageUnknownInitializer (ETL\Ingestor\StructuredFileIngestor), start_time: 1649086122.6424, end_time: 1649086122.7112, elapsed_time: 0.0688, records_examined: 1, records_loaded: 1)
2022-04-04 15:28:42 [notice] (action: xdmod.jobs-cloud-common.MemoryBucketGenerator (ETL\Ingestor\StructuredFileIngestor), start_time: 1649086122.7708, end_time: 1649086122.8422, elapsed_time: 0.07134, records_examined: 8, records_loaded: 8)
2022-04-04 15:28:42 [notice] (action: xdmod.jobs-cloud-common.ProcessorBucketGenerator (ETL\Ingestor\StructuredFileIngestor), start_time: 1649086122.9023, end_time: 1649086122.9743, elapsed_time: 0.07199, records_examined: 7, records_loaded: 7)
2022-04-04 15:28:43 [notice] Finished processing section 'xdmod.jobs-cloud-common'
2022-04-04 15:28:43 [error] {"message":"ETL\\DataEndpoint\\DirectoryScanner (name=Open Stack event logs, path=\/etc\/xdmod\/etl\/etl_data.d\/openstack, handler=jsonfile): Path '\/etc\/xdmod\/etl\/etl_data.d\/openstack' is not a directory"}
2022-04-04 15:28:43 [critical] Failed to shred files: ETL\EtlOverseer: Error verifying data endpoints:
ETL\DataEndpoint\DirectoryScanner (name=Open Stack event logs, path=/etc/xdmod/etl/etl_data.d/openstack, handler=jsonfile): Path '/etc/xdmod/etl/etl_data.d/openstack' is not a directory (stacktrace: #0 /usr/share/xdmod/classes/ETL/EtlOverseer.php(379): ETL\EtlOverseer->verifyDataEndpoints(Object(ETL\Configuration\EtlConfiguration), true)
#1 /usr/share/xdmod/classes/ETL/Utilities.php(281): ETL\EtlOverseer->execute(Object(ETL\Configuration\EtlConfiguration))
#2 /usr/share/xdmod/classes/OpenXdmod/Shredder/aCloud.php(62): ETL\Utilities::runEtlPipeline(Array, Object(CCR\Logger), Array)
#3 /usr/bin/xdmod-shredder(203): OpenXdmod\Shredder\aCloud->shredDirectory('openstack')
#4 /usr/bin/xdmod-shredder(22): main()
#5 {main})

Robert Bartlett Baron , said over 1 year ago
changed the name of the directory from /root/openstack, to /root/cloud_openstack - here is the run:

sh-4.2$ xdmod-shredder -f openstack -d cloud_openstack -r Cloud
2022-04-04 17:13:23 [notice] xdmod-shredder start (process_start_time: 2022-04-04 17:13:23)
2022-04-04 17:13:27 [notice] Start processing section 'xdmod.jobs-common'
2022-04-04 17:13:27 [notice] (action: xdmod.jobs-common.JobsTableManagement (ETL\Maintenance\ManageTables), start_time: 1649092407.2439, end_time: 1649092407.307, elapsed_time: 0.06304)
2022-04-04 17:13:27 [notice] (action: xdmod.jobs-common.CountableTypeIngestor (ETL\Ingestor\StructuredFileIngestor), start_time: 1649092407.3536, end_time: 1649092407.6372, elapsed_time: 0.28358, records_examined: 5, records_loaded: 5)
2022-04-04 17:13:27 [notice] (action: xdmod.jobs-common.JobRecordTypeIngestor (ETL\Ingestor\StructuredFileIngestor), start_time: 1649092407.6965, end_time: 1649092407.8585, elapsed_time: 0.16199, records_examined: 5, records_loaded: 5)
2022-04-04 17:13:28 [notice] (action: xdmod.jobs-common.JobTaskTypeIngestor (ETL\Ingestor\StructuredFileIngestor), start_time: 1649092407.9115, end_time: 1649092408.0922, elapsed_time: 0.18066, records_examined: 5, records_loaded: 5)
2022-04-04 17:13:28 [notice] (action: xdmod.jobs-common.UnitIngestor (ETL\Ingestor\StructuredFileIngestor), start_time: 1649092408.1544, end_time: 1649092408.3414, elapsed_time: 0.18699, records_examined: 6, records_loaded: 6)
2022-04-04 17:13:28 [notice] (action: xdmod.jobs-common.SubmissionVenueIngestor (ETL\Ingestor\StructuredFileIngestor), start_time: 1649092408.3883, end_time: 1649092408.5506, elapsed_time: 0.16234, records_examined: 4, records_loaded: 4)
2022-04-04 17:13:28 [notice] Finished processing section 'xdmod.jobs-common'
2022-04-04 17:13:28 [notice] Start processing section 'xdmod.ingest-organizations'
2022-04-04 17:13:28 [notice] (action: xdmod.ingest-organizations.IngestOrganizationConfig (ETL\Ingestor\StructuredFileIngestor), start_time: 1649092408.6311, end_time: 1649092408.7429, elapsed_time: 0.11187, records_examined: 1, records_loaded: 1)
2022-04-04 17:13:28 [notice] (action: xdmod.ingest-organizations.IngestOrganizationHpcdb (ETL\Ingestor\DatabaseIngestor), start_time: 1649092408.7994, end_time: 1649092408.8635, elapsed_time: 0.06416, records_examined: 0, records_loaded: 0)
2022-04-04 17:13:29 [notice] (action: xdmod.ingest-organizations.IngestOrgranizationDatawarehouse (ETL\Ingestor\DatabaseIngestor), start_time: 1649092408.9238, end_time: 1649092409.1854, elapsed_time: 0.26152, records_examined: 1, records_loaded: 1)
2022-04-04 17:13:29 [notice] Finished processing section 'xdmod.ingest-organizations'
2022-04-04 17:13:29 [notice] Start processing section 'xdmod.ingest-resource-types'
2022-04-04 17:13:29 [notice] (action: xdmod.ingest-resource-types.ResourceTypesStagingTableManagement (ETL\Maintenance\ManageTables), start_time: 1649092409.2683, end_time: 1649092409.2879, elapsed_time: 0.01958)
2022-04-04 17:13:29 [notice] Processing SQL file '/etc/xdmod/etl/etl_sql.d/cloud_openstack/unknown_resource_type.sql' using delimiter '//' containing 2 statements
2022-04-04 17:13:29 [notice] Finished Processing 2 SQL statements
2022-04-04 17:13:29 [notice] (action: xdmod.ingest-resource-types.ResourceTypesStagingUnknown (ETL\Maintenance\ExecuteSql), start_time: 1649092409.3319, end_time: 1649092409.4244, elapsed_time: 0.09256)
2022-04-04 17:13:29 [notice] (action: xdmod.ingest-resource-types.ResourceTypesStaging (ETL\Ingestor\StructuredFileIngestor), start_time: 1649092409.4753, end_time: 1649092409.597, elapsed_time: 0.12163, records_examined: 12, records_loaded: 12)
2022-04-04 17:13:29 [notice] (action: xdmod.ingest-resource-types.ResourceTypesHpcdb (ETL\Ingestor\DatabaseIngestor), start_time: 1649092409.6571, end_time: 1649092409.7285, elapsed_time: 0.0714, records_examined: 0, records_loaded: 0)
2022-04-04 17:13:29 [notice] (action: xdmod.ingest-resource-types.ResourceTypesDatawarehouse (ETL\Ingestor\DatabaseIngestor), start_time: 1649092409.7816, end_time: 1649092409.8637, elapsed_time: 0.08215, records_examined: 0, records_loaded: 0)
2022-04-04 17:13:29 [notice] Finished processing section 'xdmod.ingest-resource-types'
2022-04-04 17:13:29 [notice] Start processing section 'xdmod.ingest-resources'
2022-04-04 17:13:30 [notice] (action: xdmod.ingest-resources.IngestResourceConfig (ETL\Ingestor\StructuredFileIngestor), start_time: 1649092409.9488, end_time: 1649092410.0148, elapsed_time: 0.06599, records_examined: 1, records_loaded: 1)
2022-04-04 17:13:30 [notice] (action: xdmod.ingest-resources.IngestResourcesStaging (ETL\Ingestor\DatabaseIngestor), start_time: 1649092410.071, end_time: 1649092410.1378, elapsed_time: 0.06683, records_examined: 0, records_loaded: 0)
2022-04-04 17:13:30 [notice] (action: xdmod.ingest-resources.HpcdbIngestResources (ETL\Ingestor\DatabaseIngestor), start_time: 1649092410.1983, end_time: 1649092410.2662, elapsed_time: 0.06792, records_examined: 0, records_loaded: 0)
2022-04-04 17:13:30 [notice] (action: xdmod.ingest-resources.IngestResourcefact (ETL\Ingestor\DatabaseIngestor), start_time: 1649092410.3276, end_time: 1649092410.3966, elapsed_time: 0.06891, records_examined: 0, records_loaded: 0)
2022-04-04 17:13:30 [notice] (action: xdmod.ingest-resources.IngestResourceTypeRealmRelationsStaging (ETL\Ingestor\StructuredFileIngestor), start_time: 1649092410.4553, end_time: 1649092410.6518, elapsed_time: 0.1965, records_examined: 9, records_loaded: 9)
2022-04-04 17:13:30 [notice] (action: xdmod.ingest-resources.IngestInitialRealms (ETL\Ingestor\DatabaseIngestor), start_time: 1649092410.709, end_time: 1649092410.7802, elapsed_time: 0.07125, records_examined: 0, records_loaded: 0)
2022-04-04 17:13:30 [notice] (action: xdmod.ingest-resources.IngestResourcefactRealmRelations (ETL\Ingestor\DatabaseIngestor), start_time: 1649092410.8375, end_time: 1649092410.9567, elapsed_time: 0.1192, records_examined: 36, records_loaded: 36)
2022-04-04 17:13:30 [notice] Finished processing section 'xdmod.ingest-resources'
2022-04-04 17:13:31 [notice] Start processing section 'xdmod.jobs-cloud-common'
2022-04-04 17:13:31 [notice] Altering table `modw_cloud`.`event`
2022-04-04 17:13:31 [notice] Altering table `modw_cloud`.`cloud_resource_specs`
2022-04-04 17:13:31 [notice] Altering table `modw_cloud`.`session_records`
2022-04-04 17:13:31 [notice] (action: xdmod.jobs-cloud-common.CloudTableManagement (ETL\Maintenance\ManageTables), start_time: 1649092411.0442, end_time: 1649092411.3994, elapsed_time: 0.35515)
2022-04-04 17:13:31 [notice] (action: xdmod.jobs-cloud-common.CloudAssetTypeInitializer (ETL\Ingestor\StructuredFileIngestor), start_time: 1649092411.4399, end_time: 1649092411.5055, elapsed_time: 0.0656, records_examined: 5, records_loaded: 5)
2022-04-04 17:13:31 [notice] (action: xdmod.jobs-cloud-common.CloudEventTypeInitializer (ETL\Ingestor\StructuredFileIngestor), start_time: 1649092411.5575, end_time: 1649092411.627, elapsed_time: 0.06954, records_examined: 65, records_loaded: 65)
2022-04-04 17:13:31 [notice] (action: xdmod.jobs-cloud-common.CloudRecordTypeInitializer (ETL\Ingestor\StructuredFileIngestor), start_time: 1649092411.6811, end_time: 1649092411.7462, elapsed_time: 0.06506, records_examined: 4, records_loaded: 4)
2022-04-04 17:13:31 [notice] (action: xdmod.jobs-cloud-common.CloudHostUnknownInitializer (ETL\Ingestor\StructuredFileIngestor), start_time: 1649092411.7999, end_time: 1649092411.8589, elapsed_time: 0.05905, records_examined: 1, records_loaded: 1)
2022-04-04 17:13:31 [notice] (action: xdmod.jobs-cloud-common.CloudAccountUnknownInitializer (ETL\Ingestor\StructuredFileIngestor), start_time: 1649092411.9089, end_time: 1649092411.9705, elapsed_time: 0.06162, records_examined: 1, records_loaded: 1)
2022-04-04 17:13:32 [notice] (action: xdmod.jobs-cloud-common.CloudInstanceUnknownInitializer (ETL\Ingestor\StructuredFileIngestor), start_time: 1649092412.0246, end_time: 1649092412.0809, elapsed_time: 0.05632, records_examined: 1, records_loaded: 1)
2022-04-04 17:13:32 [notice] (action: xdmod.jobs-cloud-common.CloudInstanceTypeUnknownInitializer (ETL\Ingestor\StructuredFileIngestor), start_time: 1649092412.1312, end_time: 1649092412.1936, elapsed_time: 0.0624, records_examined: 1, records_loaded: 1)
2022-04-04 17:13:32 [notice] (action: xdmod.jobs-cloud-common.CloudImageUnknownInitializer (ETL\Ingestor\StructuredFileIngestor), start_time: 1649092412.2441, end_time: 1649092412.3015, elapsed_time: 0.05738, records_examined: 1, records_loaded: 1)
2022-04-04 17:13:32 [notice] (action: xdmod.jobs-cloud-common.MemoryBucketGenerator (ETL\Ingestor\StructuredFileIngestor), start_time: 1649092412.3538, end_time: 1649092412.413, elapsed_time: 0.05912, records_examined: 8, records_loaded: 8)
2022-04-04 17:13:32 [notice] (action: xdmod.jobs-cloud-common.ProcessorBucketGenerator (ETL\Ingestor\StructuredFileIngestor), start_time: 1649092412.4663, end_time: 1649092412.5268, elapsed_time: 0.06053, records_examined: 7, records_loaded: 7)
2022-04-04 17:13:32 [notice] Finished processing section 'xdmod.jobs-cloud-common'
2022-04-04 17:13:32 [notice] Start processing section 'xdmod.jobs-cloud-ingest-openstack'
2022-04-04 17:13:33 [notice] (action: xdmod.jobs-cloud-ingest-openstack.OpenStackRawCloudEventIngestor (ETL\Ingestor\StructuredFileIngestor), start_time: 1649092412.9487, end_time: 1649092413.0117, elapsed_time: 0.06305, records_examined: 0, records_loaded: 0)
2022-04-04 17:13:33 [notice] Finished processing section 'xdmod.jobs-cloud-ingest-openstack'
2022-04-04 17:13:33 [notice] Done shredding files
2022-04-04 17:13:33 [notice] xdmod-shredder end (process_end_time: 2022-04-04 17:13:33)

Even though this completes, there still is no data in the tables you mentioned.
Gregary Dean , said over 1 year ago
Ticket:  https://help.xdmod.org/support/tickets/29597

Hi Robert,

It would seem that the shredder is not finding any files to ingest data from. When using the -d flag you should specify the full path to where your openstack log files are. Instead of 'cloud_openstack', use '/root/cloud_openstack'. Using the --debug flag will also give some more output that might help track down issues. Also, the log file names should match the format %Y-%m-%dT%H:%i:%s_%Y-%m-%dT%H:%i:%s.json. The file in this directory on github is an example of the filename format, https://github.com/ubccr/xdmod/tree/xdmod10.5/tests/artifacts/xdmod/referencedata/openstack.

-greg

**Comment by rob-baron** [comment]
Gregary Dean , said over 1 year ago
Ticket:  https://help.xdmod.org/support/tickets/29597

Hi Robert,

I think your filename is in the wrong format. There should be colons between the hours, seconds, and minutes instead of dashes. Here's what the filename should be,  2018-04-17T00:00:00_2018-04-30T23:59:59.json.

-greg
Robert Bartlett Baron , said over 1 year ago
The Data is getting in to those tables, but is still not viewable though the interface.

MariaDB [(none)]> select count(*) from modw_cloud.openstack_staging_event;
+----------+
| count(*) |
+----------+
|     1827 |
+----------+
1 row in set (0.00 sec)

MariaDB [(none)]> select count(*) from modw_cloud.event;
+----------+
| count(*) |
+----------+
|     1827 |
+----------+
1 row in set (0.01 sec)

MariaDB [(none)]> select count(*) from modw_cloud.session_records;
+----------+
| count(*) |
+----------+
|      261 |
+----------+
1 row in set (0.00 sec)


Robert Bartlett Baron , said over 1 year ago
Ok, now the data is being displayed in the interface.


Robert Bartlett Baron , said over 1 year ago
Sorry, I was being bone headed about the specific format of the filename.  Interesting design choice.
Gregary Dean , said over 1 year ago
Ticket:  https://help.xdmod.org/support/tickets/29597


Hi Robert,

Great! I'm glad to hear that you're able to see the data.

-greg

 



Robert Bartlett Baron , said over 1 year ago
We can close this ticket.
This ticket has been Closed | over 1 year ago [Reply](https://help.xdmod.org/support/tickets/29597#reply-to-ticket)
